load("@rules_renode//renode:defs.bzl", "renode_interactive")

# An example showing how to launch an interactive Renode Monitor
renode_interactive(
    name = "renode-interactive-session",
    arguments = [
        "--console",
    ],
    resc = "test.resc",
    variables = {
        "CPU_PC": "0x100",
    },
    variables_with_label = {
        "ADDITIONAL_FILE": "additional_file.resc",
    },
    deps = [
        "test.repl",
    ],
)
